### ISSUE TITLE
In some instances, content remains hidden until after slide down animation completes

### ISSUE THREAD

**Issue by philbuchanan** [philbuchanan/Accordion-Blocks#45]
`hidden` attribute should be removed _before_ animating the content.

This is particularly problematic if the site stylesheet has this CSS:

```css
[hidden] {
    display: none;
}
```
